name: Run unit tests & lint
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install
      - name: Install dependencies
        run: npm install

      # Build
      - name: Build
        run: npm run build

      # Lint
      - name: Lint
        run: npm run lint

      # Test
      - name: Test
        run: npm run test
